language: node_js
node_js:
  - "6"

notifications:
  webhooks: 
    urls:
      - https://your-twilio-functions-domain.com
    on_success: never   # default: always
    on_failure: always  # default: always
    on_start: never     # default: never
    on_cancel: never    # default: always
    on_error: always    # default: always
  email: false
