language: node_js
node_js:
  - "node"

notifications:
  webhooks: 
    urls:
      - https://silent-beam-2911.twil.io/travis
    on_success: never   # default: always
    on_failure: always  # default: always
    on_start: never     # default: never
    on_cancel: never    # default: always
    on_error: always    # default: always
  email: false
